baseURL = "https://LucasPlacentino.github.io/hub-o-demo"
languageCode = "en-us"
title = "hub-o demo"
theme = "hub-o"
#themeDir = "themes"

publishDir = "docs"

#[ module ]
#[[ module.imports ]]
#  path = 'github.com/LucasPlacentino/hub-o'

[ params ]
BackgroundImages = [
  "bg/b1920-000.jpg",
  "bg/b1920-001.jpg"
]
Favicon = "favicon.ico"
BackgroundStyle = "#657383"
OpenLinksInNewWindow = true
side_menu_bar = true

[[ params.nav ]]
name = "favorites"
tag = "favorite"
icon = "star"

[[ params.nav ]]
name = "search"
tag = "search"
icon = "search"

[[ params.nav ]]
name = "shopping"
tag = "shopping"
icon = "shopping-basket"

[[ params.nav ]]
name = "music"
tag = "music"
icon = "headphones"

[[ params.nav ]]
name = "video"
tag = "video"
icon = "video-camera"
