name: GitHub Pages deploy Hub-o demo site

on:
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch the Hub-o theme
          fetch-depth: 0         # Fetch all history for .GitInfo and .Lastmod
          
#      - run: cd /home/runner/work/hub-o-demo/hub-o-demo
#      - run: mkdir themes
#      - run: cd themes
#      - run: git submodule add --force https://github.com/LucasPlacentino/hub-o
#      - run: git clone https://github.com/LucasPlacentino/hub-o
#      - run: cd ..

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

#      - run: find /home/runner/work -name package-lock.json
#      - run: find /home/runner/work -name hub-o -type d
#      - run: find /home/runner/work -name themes -type d

#      - name: Setup Node
#        uses: actions/setup-node@v3
#        with:
#          node-version: '16.18.0'
#          cache: 'npm'
          # The action defaults to search for the dependency file (package-lock.json,
          # npm-shrinkwrap.json or yarn.lock) in the repository root, and uses its
          # hash as a part of the cache key.
          # https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
#          cache-dependency-path: '/home/runner/work/hub-o-demo/hub-o-demo/themes/hub-o/package-lock.json'

#      - run: npm ci
      - run: hugo --minify

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
